ls:
  src:
    .dir: regex:[a-z0-9]*[A-Z][A-Z0-9]*[a-z][A-Za-z0-9]* | kebab-case
    .js: regex:[a-z0-9]*[A-Z][A-Z0-9]*[a-z][A-Za-z0-9]* | camelCase | kebab-case
    .ts: regex:[a-z0-9]*[A-Z][A-Z0-9]*[a-z][A-Za-z0-9]* | camelCase | kebab-case
    .d.ts: regex:[a-z0-9]*[A-Z][A-Z0-9]*[a-z][A-Za-z0-9]* | camelCase | kebab-case
    .spec.ts: regex:[a-z0-9]*[A-Z][A-Z0-9]*[a-z][A-Za-z0-9]* | camelCase | kebab-case
    .stories.ts: regex:[a-z0-9]*[A-Z][A-Z0-9]*[a-z][A-Za-z0-9]* | camelCase | kebab-case
